/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/student/route'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student/profile'
import { Route as AuthenticatedStudentQrRouteImport } from './routes/_authenticated/student/qr'
import { Route as AuthenticatedStudentStatusRouteImport } from './routes/_authenticated/student/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/auth/student',
  path: '/auth/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentQrRoute = AuthenticatedStudentQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedStudentRouteRoute,
} as any)
const AuthenticatedStudentStatusRoute =
  AuthenticatedStudentStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/student': typeof AuthStudentRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/qr': typeof AuthenticatedStudentQrRoute
  '/student/status': typeof AuthenticatedStudentStatusRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/student': typeof AuthStudentRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/qr': typeof AuthenticatedStudentQrRoute
  '/student/status': typeof AuthenticatedStudentStatusRoute
  '/student': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/auth/admin': typeof AuthAdminRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/student': typeof AuthStudentRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/qr': typeof AuthenticatedStudentQrRoute
  '/_authenticated/student/status': typeof AuthenticatedStudentStatusRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/auth/admin'
    | '/auth/register'
    | '/auth/student'
    | '/student/profile'
    | '/student/qr'
    | '/student/status'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth/admin'
    | '/auth/register'
    | '/auth/student'
    | '/student/profile'
    | '/student/qr'
    | '/student/status'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/student'
    | '/auth/admin'
    | '/auth/register'
    | '/auth/student'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/qr'
    | '/_authenticated/student/status'
    | '/_authenticated/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthStudentRoute: typeof AuthStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/auth/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/qr': {
      id: '/_authenticated/student/qr'
      path: '/qr'
      fullPath: '/student/qr'
      preLoaderRoute: typeof AuthenticatedStudentQrRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/student/status': {
      id: '/_authenticated/student/status'
      path: '/status'
      fullPath: '/student/status'
      preLoaderRoute: typeof AuthenticatedStudentStatusRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
  }
}

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentQrRoute: typeof AuthenticatedStudentQrRoute
  AuthenticatedStudentStatusRoute: typeof AuthenticatedStudentStatusRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
    AuthenticatedStudentQrRoute: AuthenticatedStudentQrRoute,
    AuthenticatedStudentStatusRoute: AuthenticatedStudentStatusRoute,
    AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRoute
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRoute,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthStudentRoute: AuthStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
